config/routes.rb
EvalApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  root "users#index"
  match '/new', to: 'users#new', via: 'get'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  validates(:name, presence: true, uniqueness: true)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to action: "index"
    else
      render 'new'
    end
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Eval App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/create.html.erb
<% provide(:title, 'Create') %>
<div class="row">
  <h1>Create a New User Here</h1>
  <p>Don't worry...we don't validate.</p>
</div>
<div class = "row">
  <%= form_for(@user) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit "Create User", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<div class="row">
  <h1>Welcome to the User portal</h1>
  <p>Add or view any user in our database. Now with absolutely no privacy!</p>
</div>
<div class = "row">
  <%= link_to("Create a New User", new_path) %>
</div>
<div class="row">
  <ul>
    <% @users.each do |user| %>
      <li>
        <%= link_to user.name, user_path(user) %></li>
    <% end %>
  </ul>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Create') %>
<div class="row">
  <h1>Create a New User Here</h1>
  <p>Don't worry...we don't validate.</p>
</div>
<div class = "row">
  <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit "Create User", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, 'User') %>
  <div class="row">
    <h1><%= @user.name %></h1>
  </div>
  <div class="row">
    <div class="col-md-6">
      <p>Following</p>
      <ul>
        <li></li>
      </ul>
    </div>
    <div class="col-md-6">
      <p>Followers</p>
      <ul>
        <li></li>
      </ul>
    </div>
  </div>